web-app/config/routes.rb
require "resque_web"
Rails.application.routes.draw do

  get 'purchases/shop'

  mount ResqueWeb::Engine => "/resque_web"

	get 'customer_users/edit_personal_information'
	get 'customer_users/edit_billing_information'

	# User Accessible Site

	# Shop
	get 	'shop',							to: 'purchases#shop'
	get 	'add-to-cart/:id',				to: 'purchases#add_to_cart'
	post	'add-to-cart',					to: 'purchases#create_order'
	get		'cart-overview',				to: 'purchases#cart_overview',			as: 'cart_overview'
	delete  'cancel-order/:id',				to: 'purchases#delete_order',			as: 'delete_order'
	post 	'orders/purchase',				to: 'purchases#create',					as: 'purchase_orders'
	get		'successful-transaction/:id', 	to: 'purchases#successful_purchase',	as: 'successful_transaction'

	devise_for :customer_users, controllers: { registrations: 'registrations', passwords: 'api/v1/customer_user_passwords' }
	authenticated :customer_user do
		root 'dashboard#index', as: "authenticated_root"
	end
	devise_scope :customer_user do
		root "devise/sessions#new"
	end
	resources :customers, only: [:create, :update]
	resources :invoices, only: [:show, :index] do
		post 'submit_payment', on: :collection
	end
	resources :receipts, only: [:index, :show] do
		get 'summative_receipt', as: :summative, on: :collection
	end	

	resources :customer_users do
		get :edit_personal_information, on: :collection
		get :edit_billing_information, on: :collection
		post :update_card, on: :collection
		post :add_card, on: :collection
		post :unlink_card, on: :collection
		post :update_auto_pay, on: :collection
	end

	resources :locations do
		get 'get_address', on: :collection
		get 'get_minimum_age', on: :collection
		get 'before_and_after_school_availability', on: :collection
	end
	resources :programs do
		get 'get_capacity', on: :collection
		get 'get_single_day_dates', on: :collection
		get 'get_program', 		on: :collection
		get 'get_summer_camp_weeks', on: :collection
		get 'get_vacation_camp_schedules', on: :collection
	end

	

	get 'registration_information' => 'dashboard#registration_information'
	get '/registration_information/:id', to: 'dashboard#registration_information_show', as: 'registration_information_show'

	resources :cit_records, only: :create
	get 'cit_registration' => 'cit_records#registration'
	get 'cit-registration' => 'cit_records#registration'

	resources :registration_records, only: :create
	get 'single_day' => 'registration_records#single_day'
	get 'single-day' => 'registration_records#single_day'
	get 'single-day-terms-of-service' => 'static_pages#single_day_terms_of_service'

	get 'request_day_care_tour' => 'registration_records#request_day_care_tour'
	get 'request-day-care-tour' => 'registration_records#request_day_care_tour'
	get 'request-day-care-tour-terms-of-service' => 'static_pages#request_day_care_tour_terms_of_service'

	get 'day_care' => 'registration_records#day_care'
	get 'day-care' => 'registration_records#day_care'

	get 'before_and_afterschool' => 'registration_records#before_and_afterschool'
	get 'before-and-afterschool' => 'registration_records#before_and_afterschool'
	get 'before-and-afterschool-terms-of-service' => 'static_pages#before_and_afterschool_terms_of_service'
	get 'before-and-afterschool-rates' => 'static_pages#before_and_after_school_rates'
	get 'no-deposit-before-and-afterschool' => 'registration_records#no_deposit_before_and_afterschool'

	get 'groupon-summer-camp' => 'registration_records#groupon_summer_camp'
	get 'summer_camp' => 'registration_records#summer_camp'
	get 'summer-camp' => 'registration_records#summer_camp'
	get 'summer-camp-terms-of-service' => 'static_pages#summer_camp_terms_of_service'

	get 'vacation_camp' => 'registration_records#vacation_camp'
	get 'vacation-camp' => 'registration_records#vacation_camp'
	get 'vacation-camp-terms-of-service' => 'static_pages#vacation_camp_terms_of_service'

	get 'success' => 'registration_records#success'
	get 'cit_success' => 'cit_records#success'

	

	# Admin Panel
	namespace :admin do
		get '' => 'registration_records#index'
		get 'home' => 'registration_records#index'
		get 'dashboard' => 'dashboard#dashboard'
		get 'payroll' => 'payrolls#home'

		# shop
		get 'shop-purchases', 		to: 'purchases#index',		as: 'shop_purchases'
		get 'purchase-details/:id',	to: 'purchases#details',	as: 'purchase_details'

		# products
		get 'products',				to:	'products#index'

		devise_for :users, controllers: { omniauth_callbacks: "admin/omniauth_callbacks", registrations: "admin/registrations", sessions: "admin/sessions" }
		authenticated :user do
			root 'registration_records#index', as: "authenticated_root"
		end
		devise_scope :user do
			root "devise/sessions#new"
		end
        get  'new-invoices/:id'     => 'registration_records#new_invoices'   , as: 'new_invoices'
        patch 'create-invoices/:id'  => 'registration_records#create_invoices', as: 'create_invoices'

		get '/payment_records/:id' => 'registration_records#show' # makes old routes work still
		resources :registration_records do
			put 'approve', on: :member
			put 'email', on: :member
		end
		resources :cit_records
		resources :locations
		resources :programs
		resources :discounts
		resources :invoices
		resources :customers

		# new vacation_camp_schedule
		get		'programs/:id/new_vacation_camp_schedule',		to: 'programs#new_vacation_camp_schedule', as: 'new_camp_schedule'
		post	'programs/create_new_vacation_camp_schedule',	to: 'programs#create_vacation_camp_schedule', as: 'create_camp_schedule'
        
        # update vacation camp enrollment
		post    'update_vacation_camp_enrollment',              to: 'registration_records#update_vacation_camp_enrollment', as: 'update_vacation_record'
		
		scope :api do
			get 	'monthly-summary',			to: 'api/dashboard#monthly_summary'
			get 	'yearly-summary',			to: 'api/dashboard#yearly_summary'
			get 	'search-customer',			to: 'api/dashboard#search_customer'
			get 	'customer-information',		to: 'api/dashboard#customer_information'
			get 	'program-breakdown', 		to: 'api/dashboard#program_breakdown'
			get 	'programs-summary',			to: 'api/dashboard#programs_summary'
			get		'receipt-information/:id',	to: 'api/dashboard#receipt_information'
			post 	'update-receipt',			to: 'api/dashboard#receipt_update'
		end

		# payroll routes
		scope :payroll do
			get		'accessible-locations/:id',									to: 'payrolls#retrieve_accessible_payroll_locations'
			post	'add-new-payroll-employee', 								to: 'payrolls#add_new_payroll_employee'
			get		'retrieve-payroll-location-information/:location_id/:date',	to: 'payrolls#retrieve_payroll_location_information'
			post	'delete-payroll-employee',									to: 'payrolls#delete_payroll_employee'
			post	'update-payroll-employee-information',						to: 'payrolls#update_payroll_employee_information'
			post	'create-payroll-hour-for-new-employee',						to: 'payrolls#create_payroll_hour_for_new_employee'
			post	'update-payroll-employee-logged-hours',						to: 'payrolls#update_payroll_employee_logged_hours'
			get		'retrieve-all-payroll-locations',							to: 'payrolls#retrieve_all_payroll_locations'
			post	'add-new-payroll-location',									to: 'payrolls#add_new_payroll_location'
			get		'retrieve-all-administrators',								to: 'payrolls#retrieve_all_administrators'
			get		'retrieve-all-authorized-administrators/:location_id',		to: 'payrolls#retrieve_all_authorized_administrators'
			post	'revoke-access-to-payroll-location',						to: 'payrolls#revoke_access_to_payroll_location'
			post	'authorize-access-to-payroll-location',						to: 'payrolls#authorize_access_to_payroll_location'
			post	'update-payroll-location-name',								to: 'payrolls#update_payroll_location_name'
			get		'retrieve-all-payroll-locations-breakdown/:year/:month',	to: 'payrolls#retrieve_all_payroll_locations_breakdown'
			get		'retrieve-all-employees-of-payroll-location/:location_id',	to: 'payrolls#retrieve_all_employees_of_payroll_location'
			post	'log-employee-absence',										to: 'payrolls#log_employee_absence'
			get		'payroll-trend-analysis/:year/:month/:location_id',			to: 'payrolls#retrieve_payroll_location_information_for_trend_analysis'
		end
	end

	# API
	namespace :api, default: { format: :json } do
		scope :v1 do
			post '/test' 							=> 'v1/payments#test'
			post '/payments' 						=> 'v1/payments#create'
			post '/invoices' 						=> 'v1/invoices#generate' # callback api for temporize to generate invoices
			post '/invoices/overdue/end-of-month-afterschool-notification'		=> 'v1/invoices#end_of_month_afterschool_ultimatum' # callback for overdue invoices every end of month for families
			post '/invoices/overdue/fee'			=> 'v1/invoices#generate_late_fees' # generate overdue fees
			post '/invoices/autopay'				=> 'v1/invoices#autopay_invoices' # autopay invoices
			post '/invoices/overdue/one-week'		=> 'v1/invoices#overdue_by_one_week' # send email notification for customer and Tom every 5th of the month
			post '/invoices/unpaid/daycare'			=> 'v1/invoices#notify_tom_for_unpaid_daycare_invoices'
			post '/records/obsolete/afterschool'	=> 'v1/obsolete_records#update_obsolete_before_and_afterschool_records' # update obsolete after school registrations
			post '/records/obsolete/single-day'		=> 'v1/obsolete_records#update_obsolete_single_day_registrations' # obsolete single day registrations
			post '/records/obsolete/summer-camp'	=> 'v1/obsolete_records#update_obsolete_summer_camp_registrations' # obsolete summer camp registrations
			post '/records/obsolete/vacation-camp'	=> 'v1/obsolete_records#update_obsolete_vacation_camp_registrations' # obsolete vacation camp records
			post '/invoices/overdue/last-month'		=> 'v1/invoices#unpaid_invoices_last_month'
			post '/invoices/unpaid/after-school'	=> 'v1/invoices#unpaid_afterschool_invoices'
            post '/invoices/summer-camp/due'        => 'v1/invoices#due_summer_camp_invoices'
			post '/invoices/summer-camp/overdue'    => 'v1/invoices#overdue_summer_camp_invoices'

web-app/app/helpers/application_helper.rb
module ApplicationHelper
	def how_did_you_hear_about_us_options
		[['Friend', 'friend'], ['Internet Search', 'internetSearch'], ['Facebook', 'facebook'], ['Advertising', 'advertising'], ['Other', 'other']]
	end

	def single_day_locations
		[['Clifton Park', 'cliftonPark'], ['East Greenbush', 'eastGreenbush'], ['Guilderland - Christ Lutheran Church', 'guilderlandChristLutheranChurch'], ['Guilderland - School House Road', 'guilderlandSchoolHouseRoad'], ['Niskayuna', 'niskayuna'], ['Troy', 'troy']]
	end

	def single_day_days
		[['Columbus Day', 'columbusDay'], ['Rosh Hashanah', 'roshHashanah'], ['Yom Kippur', 'yomKippur'], ['Election Day', 'electionDay'], ['Veterans Day', 'veteransDay'], ['Thanksgiving Eve', 'thanksgivingEve'], ['Martin Luther King Day', 'martinLutherKingDay'], ['Conference Day', 'conferenceDay'], ['Good Friday', 'goodFriday']]
	end

	def searchable_single_day_days
		[['Columbus Day', 'columbusDay'], ['Rosh Hashanah', 'roshHashanah'], ['Yom Kippur', 'yomKippur'], ['Election Day', 'electionDay'], ['Veterans Day', 'veteransDay'], ['Thanksgiving Eve', 'thanksgivingEve'], ['Martin Luther King Day', 'martinLutherKingDay'], ['Conference Day', 'conferenceDay'], ['Good Friday', 'goodFriday']]
	end

	def cit_locations
		[['Clifton Park', 'cliftonPark'], ['Duanesburg', 'duanesburg'], ['East Greenbush', 'eastGreenbush'], ['Guilderland - Christ Lutheran Church', 'guilderlandChristLutheranChurch'], ['Guilderland - School House Road', 'guilderlandSchoolHouseRoad'], ['Niskayuna', 'niskayuna'], ['Troy', 'troy'], ['Rotterdam/Schalmont', 'rotterdamSchalmont']]
	end

	def vacation_camp_locations
		[['Clifton Park', 'cliftonPark'], ['East Greenbush', 'eastGreenbush'], ['Guilderland - Christ Lutheran Church', 'guilderlandChristLutheranChurch'], ['Guilderland - School House Road', 'guilderlandSchoolHouseRoad'], ['Niskayuna', 'niskayuna'], ['Troy', 'troy']]
	end

	def vacation_camp_months
		[['April 2018'], ['December 2018']]
	end

	def searchable_vacation_camp_months
		[['December 2018', 'december2018'], ['February 2019', 'february2019'], ['April 2019', 'april2019']]
	end

	def number_to_word(number)
		case number
		when 1
			"one"
		when 2
			"two"
		when 3
			"three"
		when 4
			"four"
		when 5
			"five"
		when 6
			"six"
		when 7
			"seven"
		when 8
			"eight"
		when 9
			"nine"
		when 10
			"ten"
		end
	end

	def months
		[
			'january', 'february', 'march', 'april',
			'may', 'june', 'july', 'august', 'september',
			'october', 'november', 'december'
		]
	end

	def vacation_camp_date(month, day_of_the_week)
		if month == 'december'
			case day_of_the_week
			when 'Wed'
				", 26"
			when 'Thurs'
				", 27"
			when 'Fri'
				", 28"
			end
		elsif month == 'february'
			case day_of_the_week
			when 'Mon'
				", 18"
			when 'Tues'
				", 19"
			when 'Wed'
				", 20"
			when 'Thurs'
				", 21"
			when 'Fri'
				", 22"
			end
		elsif month == 'april'
			case day_of_the_week
			when 'Mon'
				", 22"
			when 'Tues'
				", 23"
			when 'Wed'
				", 24"
			when 'Thurs'
				", 25"
			when 'Fri'
				", 26"
			end
		end
	end

	def parse_error_message(message)
		message
	end

	def current_year
		Date.today.year.to_s
	end

	def current_month
		Time.now.strftime("%B").downcase
	end

	def get_card_icon card_brand
		case card_brand.downcase
		when "visa"
			'/assets/cards/visa.png'
		when "mastercard"
			'/assets/cards/master-card.png'
		when 'discover'
			'/assets/cards/discover.png'
		when 'american express'
			'/assets/cards/american-express.png'
		when 'amazon'
			'/assets/cards/amazon.png'
		when 'cirrus'
			'/assets/cards/cirrus.png'
		when 'diners club'
			'/assets/cards/diners-club.png'
		when 'direct debit'
			'/assets/cards/direct-debit.png'
		when 'ebay'
			'/assets/cards/ebay.png'
		when 'eway'
			'/assets/cards/eway.png'
		when 'jcb'
			'/assets/cards/jcb.png'
		when 'maestro'
			'/assets/cards/maestro.png'
		when 'paypal'
			'/assets/cards/paypal.png'
		when 'sage'
			'/assets/cards/sage.png'
		when 'shopify'
			'/assets/cards/shopify.png'
		when 'skrill'
			'/assets/cards/skrill.png'
		when 'solo'
			'/assets/cards/solo.png'
		when 'western union'
			'/assets/cards/western-union.png'
		else
			'/assets/cards/w.png'
		end
	end

    def format_promo_name promo_name
        promo_name.gsub('_', ' ').titleize
    end

    def summer_camp_registration_type summer_camp_rec
        if summer_camp_rec.promo_name.present?
            summer_camp_rec.promo_name.gsub("_", ' ') + " promo package"
        else
            "Regular registration"
        end
    end

    def summer_camp_weeks_enrolled summer_camp_rec
        result = ""
        summer_camp_rec.attributes.each do |attr_name, attr_value|
            if attr_value.class == TrueClass || attr_value.class == FalseClass
                if attr_value == true
                    result << "<li>#{parse_summer_camp_week_name(attr_name)}</li>"
                end
            end
        end
        result.html_safe
    end

    def before_and_after_school_schedule before_and_after_school_rec
       result = []
       before_and_after_school_rec.attributes.each do |attr_name, attr_value|
            if attr_value.class == TrueClass || attr_value.class == FalseClass
                if attr_value == true
                    result << attr_name
                end
            end
       end
       result
    end

    def create_vacation_camp_schedule_button registration_rec, sched
        vacation_camp_enrollments = registration_rec.vacation_camp_records.pluck(:vacation_camp_schedule_id)
        enrolled_to_camp_schedule = false
        if vacation_camp_enrollments.any? {|enrollment_id| enrollment_id == sched.id}
            "<button class='vacation-camp-toggle-enrollment' data-regis-record-id=#{registration_rec.id} " \
                "data-schedule-id=#{sched.id} type='button' id='camp-sched-#{sched.id}'>Unenroll</button>".html_safe
        else
            "<button class='vacation-camp-toggle-enrollment' data-regis-record-id=#{registration_rec.id} " \
                "data-schedule-id=#{sched.id} type='button' id='camp-sched-#{sched.id}'>Enroll</button>".html_safe
        end
    end

    private

    def parse_summer_camp_week_name camp_week
        case camp_week
            when "week_one"
                "Week 1"
            when "week_two"
                "Week 2"
            when "week_three"
                "Week 3"
            when "week_four"
                "Week 4"
            when "week_five"
                "Week 5"
            when "week_six"
                "Week 6"
            when "week_seven"
                "Week 7"
            when "week_eight"
                "Week 8"
            when "week_nine"
                "Week 9"
            when "week_ten"
                "Week 10"
        end
    end

end

web-app/app/views/layouts/application/_alerts.html.erb
<% if @trigger %>
	<p class="alert alert-success"><span class="close">⊗</span>Welcome! You have signed up successfully.</p>
<% else %>
	<% if notice %>
	  <p class="alert alert-success"><span class="close">⊗</span><%= notice %></p>
	<% end %>
	<% if alert %>
	  <p class="alert alert-danger"><span class="close">⊗</span><%= alert %></p>
	<% end %>
<%end%>

web-app/app/views/layouts/application/_header.html.erb
<nav class="nav-element" id="nav">
    <div class="nav-links-container" id="navigation-links">
        <div class="logo-container">
            <%= image_tag('new-logo.png', class: "tsl-logo") %>
        </div>
            <% if customer_user_signed_in? %>
                <div class="nav-links" id="nav-links">
                    <%= link_to "Home", authenticated_root_path, class: '' %>
                    <%= link_to "Update Payment Information", edit_billing_information_customer_users_path, class: '' %>
                    <div class="billing-menu">
                        <span class="">Billing</span>
                       <div class="billing-arrow">
                       </div>
                        <div class="billing-options">
                            <ul class="">
                                <li class=""><i class="fas fa-file-invoice"></i><%= link_to "Invoices", invoices_path, class: '' %></li>
                                <li class=""><i class="fas fa-receipt"></i><%= link_to "Receipts", receipts_path, class: '' %></li>
                                <% if current_customer_user.customer && current_customer_user.customer.stripe_customer_identifier.present? %>
                                    <li class=""><i class="fas fa-history"></i> <%= link_to "Billing History", "javascript:void(0)", class: '', id: 'billing' %></li>
                                    <script type="text/javascript">
                                        var handler = AccountDock.configure({
                                            key: '<%= ENV["ACCOUNT_DOCK_KEY"] %>',
                                            customer: '<%= current_customer_user.customer.stripe_customer_identifier %>'
                                        });
                                        $(function(){
                                            $('#billing').on(
                                            'click',
                                            function(event) {
                                                event.preventDefault();
                                                handler.open();
                                            }
                                            );
                                        });
                                    </script>
                                <% end %>
                            </ul>
                        </div>
                    </div>
                    <div class="account-menu account-nav">
                        <span class="account-nav">Account</span>
                        <div class="account-arrow account-nav">
                        </div>
                        <div class="account-options account-nav">
                            <ul class="account-nav">
                                <li class="account-nav">
                                    <i class="fas fa-info"></i>
                                    <%= link_to "Registration Information", registration_information_path, class: 'account-nav' %>
                                </li>
                                <li class="account-nav">
                                    <i class="fas fa-cog"></i>
                                     <%= link_to "Account Settings", edit_customer_user_registration_path, class: 'account-nav' %>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <%= link_to "Shop", shop_path %>
                    <%= link_to "Logout", destroy_customer_user_session_path, method: :delete %>
                </div>

                <div class="nav-links-mobile" id="nav-links-mobile">
                    <div class="nav-links-mobile-container">
                         <i class="fas fa-bars" id="mobile-nav"></i>
                         <div class="nav-links-mobile-menu">
                             <div class="nav-links-mobile-menu-container">
                                 <ul>
                                    <li><i class="fas fa-home"></i><%= link_to 'Home', authenticated_root_path %></li>
                                    <li><%= link_to "Shop", shop_path  %><i class="fas fa-store"></i></li>
                                    <li><i class="far fa-credit-card"></i><%= link_to "Update Payment Information", edit_billing_information_customer_users_path, class: '' %></li>
                                    <li class="mobile-billing-option">
                                        <i class="fa fa-less-than"></i>
                                        <div class="text">Billing</div>
                                        <div class="option" id="mobile-billing-menu">
                                            <ul>
                                                <li>
                                                    <i class="fas fa-file-invoice"></i>
                                                    <%= link_to "Invoices", invoices_path, class: '' %>    
                                                </li>
                                                <li>
                                                    <i class="fas fa-receipt"></i>
                                                    <%= link_to "Receipts", receipts_path, class: '' %>
                                                </li>
                                            </ul>
                                        </div>
                                    </li>
                                     <li id="mobile-account-option">
                                        <i class="fa fa-less-than"></i>
                                        <div class="text">Account</div>
                                        <div class="option" id="mobile-account-menu">
                                            <ul>
                                                <li class="account-nav">
                                                    <i class="fas fa-info"></i>
                                                    <%= link_to "Registrations", registration_information_path, class: 'account-nav' %>
                                                </li>
                                                <li class="account-nav">
                                                    <i class="fas fa-cog"></i>
                                                    <%= link_to "Settings", edit_customer_user_registration_path, class: 'account-nav' %>
                                                </li>
                                            </ul>
                                        </div>
                                     </li>
                                     <li><i class="fas fa-sign-out-alt"></i><%= link_to "Logout", destroy_customer_user_session_path, method: :delete %></li>
                                 </ul>
                             </div>
                         </div>
                    </div>
                </div>
            <% else %>
                <div class="session-links">
                   <div class="mobile-view" id="mobile-view">
                       <i class="fas fa-bars" id="bars-icon"></i>
                       <div class="menu-options" id="menu-options">
                           <ul>
                               <li><%= link_to "Log In", new_customer_user_session_path %><i class="fas fa-sign-in-alt"></i></li>
                               <li><%= link_to "Register", new_customer_user_registration_path  %><i class="fas fa-user-plus"></i></li>
                               <li><%= link_to "Shop", shop_path  %><i class="fas fa-store"></i></li>
                           </ul>
                       </div>
                   </div>
                   <div class="regular-view">
                        <%= link_to "Log In", new_customer_user_session_path %>
                        <%= link_to "Register", new_customer_user_registration_path  %>
                        <%= link_to "Shop", shop_path %>
                   </div>
                </div>
            <% end %>
    </div>
</nav>