web-app/config/routes.rb
require "resque_web"
Rails.application.routes.draw do

  get 'purchases/shop'

  mount ResqueWeb::Engine => "/resque_web"

	get 'customer_users/edit_personal_information'
	get 'customer_users/edit_billing_information'

	# User Accessible Site

	# Shop
	get 	'shop',							to: 'purchases#shop'
	get 	'add-to-cart/:id',				to: 'purchases#add_to_cart'
	post	'add-to-cart',					to: 'purchases#create_order'
	get		'cart-overview',				to: 'purchases#cart_overview',			as: 'cart_overview'
	delete  'cancel-order/:id',				to: 'purchases#delete_order',			as: 'delete_order'
	post 	'orders/purchase',				to: 'purchases#create',					as: 'purchase_orders'
	get		'successful-transaction/:id', 	to: 'purchases#successful_purchase',	as: 'successful_transaction'

	devise_for :customer_users, controllers: { registrations: 'registrations', passwords: 'api/v1/customer_user_passwords' }
	authenticated :customer_user do
		root 'dashboard#index', as: "authenticated_root"
	end
	devise_scope :customer_user do
		root "devise/sessions#new"
	end
	resources :customers, only: [:create, :update]
	resources :invoices, only: [:show, :index] do
		post 'submit_payment', on: :collection
	end
	resources :receipts, only: [:index, :show] do
		get 'summative_receipt', as: :summative, on: :collection
	end	

	resources :customer_users do
		get :edit_personal_information, on: :collection
		get :edit_billing_information, on: :collection
		post :update_card, on: :collection
		post :add_card, on: :collection
		post :unlink_card, on: :collection
		post :update_auto_pay, on: :collection
	end

	resources :locations do
		get 'get_address', on: :collection
		get 'get_minimum_age', on: :collection
		get 'before_and_after_school_availability', on: :collection
	end
	resources :programs do
		get 'get_capacity', on: :collection
		get 'get_single_day_dates', on: :collection
		get 'get_program', 		on: :collection
		get 'get_summer_camp_weeks', on: :collection
		get 'get_vacation_camp_schedules', on: :collection
	end

	

	get 'registration_information' => 'dashboard#registration_information'
	get '/registration_information/:id', to: 'dashboard#registration_information_show', as: 'registration_information_show'

	resources :cit_records, only: :create
	get 'cit_registration' => 'cit_records#registration'
	get 'cit-registration' => 'cit_records#registration'

	resources :registration_records, only: :create
	get 'single_day' => 'registration_records#single_day'
	get 'single-day' => 'registration_records#single_day'
	get 'single-day-terms-of-service' => 'static_pages#single_day_terms_of_service'

	get 'request_day_care_tour' => 'registration_records#request_day_care_tour'
	get 'request-day-care-tour' => 'registration_records#request_day_care_tour'
	get 'request-day-care-tour-terms-of-service' => 'static_pages#request_day_care_tour_terms_of_service'

	get 'day_care' => 'registration_records#day_care'
	get 'day-care' => 'registration_records#day_care'

	get 'before_and_afterschool' => 'registration_records#before_and_afterschool'
	get 'before-and-afterschool' => 'registration_records#before_and_afterschool'
	get 'before-and-afterschool-terms-of-service' => 'static_pages#before_and_afterschool_terms_of_service'
	get 'before-and-afterschool-rates' => 'static_pages#before_and_after_school_rates'
	get 'no-deposit-before-and-afterschool' => 'registration_records#no_deposit_before_and_afterschool'

	get 'groupon-summer-camp' => 'registration_records#groupon_summer_camp'
	get 'summer_camp' => 'registration_records#summer_camp'
	get 'summer-camp' => 'registration_records#summer_camp'
	get 'summer-camp-terms-of-service' => 'static_pages#summer_camp_terms_of_service'

	get 'vacation_camp' => 'registration_records#vacation_camp'
	get 'vacation-camp' => 'registration_records#vacation_camp'
	get 'vacation-camp-terms-of-service' => 'static_pages#vacation_camp_terms_of_service'

	get 'success' => 'registration_records#success'
	get 'cit_success' => 'cit_records#success'

	

	# Admin Panel
	namespace :admin do
		get '' => 'registration_records#index'
		get 'home' => 'registration_records#index'
		get 'dashboard' => 'dashboard#dashboard'
		get 'payroll' => 'payrolls#home'

		# shop
		get 'shop-purchases', 		to: 'purchases#index',		as: 'shop_purchases'
		get 'purchase-details/:id',	to: 'purchases#details',	as: 'purchase_details'

		# products
		get 'products',				to:	'products#index'

		devise_for :users, controllers: { omniauth_callbacks: "admin/omniauth_callbacks", registrations: "admin/registrations", sessions: "admin/sessions" }
		authenticated :user do
			root 'registration_records#index', as: "authenticated_root"
		end
		devise_scope :user do
			root "devise/sessions#new"
		end
        get  'new-invoices/:id'     => 'registration_records#new_invoices'   , as: 'new_invoices'
        patch 'create-invoices/:id'  => 'registration_records#create_invoices', as: 'create_invoices'

		get '/payment_records/:id' => 'registration_records#show' # makes old routes work still
		resources :registration_records do
			put 'approve', on: :member
			put 'email', on: :member
		end
		resources :cit_records
		resources :locations
		resources :programs
		resources :discounts
		resources :invoices
		resources :customers

		# new vacation_camp_schedule
		get		'programs/:id/new_vacation_camp_schedule',		to: 'programs#new_vacation_camp_schedule', as: 'new_camp_schedule'
		post	'programs/create_new_vacation_camp_schedule',	to: 'programs#create_vacation_camp_schedule', as: 'create_camp_schedule'
        
        # update vacation camp enrollment
		post    'update_vacation_camp_enrollment',              to: 'registration_records#update_vacation_camp_enrollment', as: 'update_vacation_record'
		
		scope :api do
			get 	'monthly-summary',			to: 'api/dashboard#monthly_summary'
			get 	'yearly-summary',			to: 'api/dashboard#yearly_summary'
			get 	'search-customer',			to: 'api/dashboard#search_customer'
			get 	'customer-information',		to: 'api/dashboard#customer_information'
			get 	'program-breakdown', 		to: 'api/dashboard#program_breakdown'
			get 	'programs-summary',			to: 'api/dashboard#programs_summary'
			get		'receipt-information/:id',	to: 'api/dashboard#receipt_information'
			post 	'update-receipt',			to: 'api/dashboard#receipt_update'
		end

		# payroll routes
		scope :payroll do
			get		'accessible-locations/:id',									to: 'payrolls#retrieve_accessible_payroll_locations'
			post	'add-new-payroll-employee', 								to: 'payrolls#add_new_payroll_employee'
			get		'retrieve-payroll-location-information/:location_id/:date',	to: 'payrolls#retrieve_payroll_location_information'
			post	'delete-payroll-employee',									to: 'payrolls#delete_payroll_employee'
			post	'update-payroll-employee-information',						to: 'payrolls#update_payroll_employee_information'
			post	'create-payroll-hour-for-new-employee',						to: 'payrolls#create_payroll_hour_for_new_employee'
			post	'update-payroll-employee-logged-hours',						to: 'payrolls#update_payroll_employee_logged_hours'
			get		'retrieve-all-payroll-locations',							to: 'payrolls#retrieve_all_payroll_locations'
			post	'add-new-payroll-location',									to: 'payrolls#add_new_payroll_location'
			get		'retrieve-all-administrators',								to: 'payrolls#retrieve_all_administrators'
			get		'retrieve-all-authorized-administrators/:location_id',		to: 'payrolls#retrieve_all_authorized_administrators'
			post	'revoke-access-to-payroll-location',						to: 'payrolls#revoke_access_to_payroll_location'
			post	'authorize-access-to-payroll-location',						to: 'payrolls#authorize_access_to_payroll_location'
			post	'update-payroll-location-name',								to: 'payrolls#update_payroll_location_name'
			get		'retrieve-all-payroll-locations-breakdown/:year/:month',	to: 'payrolls#retrieve_all_payroll_locations_breakdown'
			get		'retrieve-all-employees-of-payroll-location/:location_id',	to: 'payrolls#retrieve_all_employees_of_payroll_location'
			post	'log-employee-absence',										to: 'payrolls#log_employee_absence'
			get		'payroll-trend-analysis/:year/:month/:location_id',			to: 'payrolls#retrieve_payroll_location_information_for_trend_analysis'
		end
	end

	# API
	namespace :api, default: { format: :json } do
		scope :v1 do
			post '/test' 							=> 'v1/payments#test'
			post '/payments' 						=> 'v1/payments#create'
			post '/invoices' 						=> 'v1/invoices#generate' # callback api for temporize to generate invoices
			post '/invoices/overdue/end-of-month-afterschool-notification'		=> 'v1/invoices#end_of_month_afterschool_ultimatum' # callback for overdue invoices every end of month for families
			post '/invoices/overdue/fee'			=> 'v1/invoices#generate_late_fees' # generate overdue fees
			post '/invoices/autopay'				=> 'v1/invoices#autopay_invoices' # autopay invoices
			post '/invoices/overdue/one-week'		=> 'v1/invoices#overdue_by_one_week' # send email notification for customer and Tom every 5th of the month
			post '/invoices/unpaid/daycare'			=> 'v1/invoices#notify_tom_for_unpaid_daycare_invoices'
			post '/records/obsolete/afterschool'	=> 'v1/obsolete_records#update_obsolete_before_and_afterschool_records' # update obsolete after school registrations
			post '/records/obsolete/single-day'		=> 'v1/obsolete_records#update_obsolete_single_day_registrations' # obsolete single day registrations
			post '/records/obsolete/summer-camp'	=> 'v1/obsolete_records#update_obsolete_summer_camp_registrations' # obsolete summer camp registrations
			post '/records/obsolete/vacation-camp'	=> 'v1/obsolete_records#update_obsolete_vacation_camp_registrations' # obsolete vacation camp records
			post '/invoices/overdue/last-month'		=> 'v1/invoices#unpaid_invoices_last_month'
			post '/invoices/unpaid/after-school'	=> 'v1/invoices#unpaid_afterschool_invoices'
            post '/invoices/summer-camp/due'        => 'v1/invoices#due_summer_camp_invoices'
			post '/invoices/summer-camp/overdue'    => 'v1/invoices#overdue_summer_camp_invoices'

web-app/app/models/program.rb
class Program < ActiveRecord::Base
  	belongs_to :director, class_name: "User"
	belongs_to :location
	has_many :registration_records, dependent: :destroy
	has_many :child_records, through: :registration_records
	has_many :discounts, dependent: :destroy
	has_many :single_day_dates, dependent: :destroy
	accepts_nested_attributes_for :single_day_dates, allow_destroy: true, reject_if: :all_blank
	has_many :summer_camp_weeks, dependent: :destroy
	accepts_nested_attributes_for :summer_camp_weeks, allow_destroy: true, reject_if: :all_blank
	has_many :vacation_camp_schedules, dependent: :destroy
	accepts_nested_attributes_for :vacation_camp_schedules, allow_destroy: true, reject_if: :all_blank
	has_one :before_and_after_school_program_configuration, dependent: :destroy
	accepts_nested_attributes_for :before_and_after_school_program_configuration
  	validates_presence_of :name, :location, :capacity
	validates_uniqueness_of :name, scope: :location

	after_create :create_before_and_after_school_program_config, if: :before_and_after_school_program?

	def display_name
		"#{location.name} #{name}"
	end

	def has_top_level_capacity?
		if name == "After School" || name == "Day Care"
			true
		else
			false
		end
	end

	def enrolled_count
		Rails.cache.fetch("/programs/#{self.id}/enrolled_count", expires_in: 12.hours) { get_enrolled_count! }
	end

	def get_enrolled_count!
		registration_records.where(enrolled: true).to_a.sum(&:child_records_count)
	end

	def vacation_camp_enrollment_count
		vacation_camp_enrollment_count = vacation_camp_schedules.inject(0) do |sum, schedule|
			sum += schedule.enrollment_count
		end
	end

    def after_school_registrations(request_type = 'enrollment_count')
        aft_recs = self.registration_records.includes(:before_and_afterschool_record)
            .where('extract (year from before_and_afterschool_records.start_date) >= ?', 2019)
            .references(:before_and_afterschool_records)
        result = aft_recs.inject([]) do |acc, curr|
            bafs_start_date = curr.before_and_afterschool_record.start_date
            if bafs_start_date.year == 2019
                if bafs_start_date.month >= 9
                    acc << curr
                else
                    acc
                end
            else
                acc << curr
            end
        end
        request_type == 'enrollment_count' ? result.sum(&:child_records_count) : result
	end
	
	def daycare_records
		self.registration_records.includes(:program)
		.where('programs.name = ?', 'Day Care')
		.references(:programs)
		.order('registration_records.created_at DESC')
	end

	private

	def create_before_and_after_school_program_config
		before_and_after_school_config = BeforeAndAfterSchoolProgramConfiguration.create
		self.before_and_after_school_program_configuration = before_and_after_school_config
	end

	def before_and_after_school_program?
		if self.name == "After School"
			true
		else
			false
		end
	end

end

web-app/app/views/registration_records/_payment_section.html.erb
<% if current_customer_user.customer.card_last_four.present? && current_customer_user.customer.card_brand.present? %>
    <p><b>Card On File:</b> <%= current_customer_user.customer.card_brand %> ending with <%= current_customer_user.customer.card_last_four %></p>
    <%= f.submit 'Submit And Pay With Card on File', class: "w-100 pointer bg-orange white ph3 pv2 dim outline-0 ba b--black-20" %>
<% else %>
    <div class="checkout-container w-100 white ph3 pv2 dim outline-0 ba ">
        <button id="checkoutSubmit">Submit and Pay</button>
    </div>
    <script>
        var checkoutWindow = StripeCheckout.configure({
            key: "<%= Rails.application.secrets.stripe_publishable_key %>",
            email: "<%= current_customer_user.email %>",
            token: function(stripeToken) {
                const form = $('form');
                form.append($('<input type="hidden" name="stripeToken" />').val(stripeToken.id));
                $(form).get(0).submit();
            }
        });
        $(document).ready(function() {
            document.getElementById('checkoutSubmit').addEventListener('click', function(e) {
                checkoutWindow.open({
                    name: 'TSL',
                    panelLabel: "Submit and Pay"
                });
                e.preventDefault();
            })
            window.addEventListener('popstate', function() {
            checkoutWindow.close();
            });
        })
    </script>
  
<% end %>

<% if current_customer_user.customer.stripe_bank_identifier.present? && current_customer_user.customer.bank_name.present? && current_customer_user.customer.bank_verified? %>
    <p><b>Bank On File:</b> <%= current_customer_user.customer.bank_name %></p>
    <%= f.submit 'Submit And Pay With Bank on File', class: "w-100 pointer bg-orange white ph3 pv2 dim outline-0 ba b--black-20" %>
<% else %>
    <p class="measure center">If you'd like to use a bank account instead, please link it below.</p>
    <%= render 'bank_form', button_label: "Link Bank Details And Pay" %>
<% end %>

web-app/app/views/registration_records/before_and_afterschool.html.erb
<div class="w-100 w-80-m w-50-l center pa3">
	<h1 class="f3 f2-ns lh-copy tc">Before and Afterschool</h1>
	<%= form_for @registration_record do |f| %>
		<% if @registration_record.errors.any? %>
			<div id="errorExplanation">
				<h2>Your were NOT charged. <%= pluralize(@registration_record.errors.count, "error") %> prohibited this record from being saved:</h2>
				<ul>
				<% @registration_record.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
				</ul>
			</div>
		<% end %>

		<div class="mb3 center">
			<h2 class="f6 lh-title ttu tracked mv0 pv3 orange relative left--1-ns">1. Pick a Location</h2>
			<div>
				<%= f.select :location, options_for_select(Location.includes(:programs).where('programs.name' => 'After School', 'programs.active' => 'true').order(:name).map{|location| [location.dropdown_display_name('After School'), location.name]}, @registration_record.location), { include_blank: true }, { class: "bg-white ba b--black-20 pa3 mb1 db", data: { program: 'After School' } } %>

				<div id="js-location">
				</div>

				<div id="js-capacity-message">
				</div>
			</div>
		</div>

		<div id="js-capacity-wrapper">
			<h2 class="f6 lh-title ttu tracked mt4 mb0 pv3 orange relative left--1-ns">2. Child(ren)’s Info</h2>
			<div id="child-records">
				<%= f.fields_for :child_records do |child_record| %>
					<%= render "child_record_fields", f: child_record %>

					<div class="links list pa0 ma0">
						<%= link_to_add_association 'Add New Child', f, :child_records, class: "pointer ph3 pv2 bg-green white outline-0 ba b--black-20 mb3 js-child-records-add" %>
					</div>
				<% end %>
			</div>
            <%= f.fields_for :before_and_afterschool_record do |before_and_afterschool_record_fields| %>
                <h2 class="f6 lh-title ttu tracked mt4 mb0 pv3 orange relative left--1-ns">3. Schedule Selection</h2>
                <div class="year-cycle-selection">
                    <div class="radio-buttons">
                        <div class="input-group">
                            <%= before_and_afterschool_record_fields.radio_button :year_cycle, '2018-2019', id: '2018_2019_radio', checked: true %>
                            <label for="2018_2019_radio">2019 <%= Time.now.to_date.strftime('%B') %> - June</label>
                        </div>
                        <div class="input-group">
                            <%= before_and_afterschool_record_fields.radio_button :year_cycle, '2019-2020', id: '2019_2020_radio' %>
                            <label for="2019_2020_radio">2019 September - 2020 June</label>
                        </div>
                        </div>
                        <div class="notice">
                        Please note that each year cycle has its own set of rates
                        <%= image_tag 'info-icon.png', class: 'info-icon' %>
                        </div>
                        <div class="rates-information">
                        For more information click <%= link_to 'here',  before_and_afterschool_rates_path, target: '_blank' %>.
                        </div>
                </div>
                <div class="record-type-selection-section">
                <h2 class="f6 lh-title ttu tracked mt4 mb0 pv3 orange relative left--1-ns">4. Registration Type Selection</h2>  
                <div class="after-school-registration-options">
                    <div class="option-pair">
                        <%= before_and_afterschool_record_fields.radio_button :registration_type, 'standard_after_school_registration', id: 'standard_after_school_registration', checked: true %>
                        <label for="standard_after_school_registration">Standard</label>
                    </div>

                    <div class="option-pair with-promo">
                        <%= before_and_afterschool_record_fields.radio_button :registration_type, 'regular_with_promo_after_school_registration', id: 'regular_with_promo_after_school_registration' %>
                        <label for="regular_with_promo_after_school_registration">Promo bundle</label>
                    </div>

                    <div class="option-pair promo-only-after-school">
                        <%= before_and_afterschool_record_fields.radio_button :registration_type, 'promo_only_registration', id: 'promo_only_registration' %>
                        <label for="promo_only_registration">Promo package: single days of care only</label>
                    </div>
                </div>
                <div class="mb3 center" id="before-and-after-school-fields">
                    <%= before_and_afterschool_record_fields.label :start_date, class: "f6 fw7 db mb1" %>
                    <%= before_and_afterschool_record_fields.text_field :start_date, id: 'before-after-school-start-date', class: "input rest ba b--black-20 pa2 mb1 db w-100 date-format", placeholder: 'yyyy-mm-dd', autocomplete: 'off' %><br/>

                    <div id="js-before-school">
                        <label class="f6 fw7 db mb1">Before School:</label>
                        <%= before_and_afterschool_record_fields.check_box :before_school_monday %>
                        <%= before_and_afterschool_record_fields.label :before_school_monday, "Monday" %>
                        <%= before_and_afterschool_record_fields.check_box :before_school_tuesday %>
                        <%= before_and_afterschool_record_fields.label :before_school_tuesday, "Tuesday" %>
                        <%= before_and_afterschool_record_fields.check_box :before_school_wednesday %>
                        <%= before_and_afterschool_record_fields.label :before_school_wednesday, "Wednesday" %>
                        <%= before_and_afterschool_record_fields.check_box :before_school_thursday %>
                        <%= before_and_afterschool_record_fields.label :before_school_thursday, "Thursday" %>
                        <%= before_and_afterschool_record_fields.check_box :before_school_friday %>
                        <%= before_and_afterschool_record_fields.label :before_school_friday, "Friday" %>
                    </div><br/>

                    <div id="js-after-school">
                        <label class="f6 fw7 db mb1">After School:</label>
                        <%= before_and_afterschool_record_fields.check_box :after_school_monday %>
                        <%= before_and_afterschool_record_fields.label :after_school_monday, "Monday" %>
                        <%= before_and_afterschool_record_fields.check_box :after_school_tuesday %>
                        <%= before_and_afterschool_record_fields.label :after_school_tuesday, "Tuesday" %>
                        <%= before_and_afterschool_record_fields.check_box :after_school_wednesday %>
                        <%= before_and_afterschool_record_fields.label :after_school_wednesday, "Wednesday" %>
                        <%= before_and_afterschool_record_fields.check_box :after_school_thursday %>
                        <%= before_and_afterschool_record_fields.label :after_school_thursday, "Thursday" %>
                        <%= before_and_afterschool_record_fields.check_box :after_school_friday %>
                        <%= before_and_afterschool_record_fields.label :after_school_friday, "Friday" %>
                    </div>
                </div>
            <% end %>
                
                <div class="annual-single-day-promo-options">
                    <h4 class="single-day-promo-header">Annual Single Days of Care Packages</h4>
                    <%= f.fields_for :annual_single_day_promo_record do |annual_package_promo| %>
                        <%= annual_package_promo.hidden_field :year_cycle, value: '2019-2020' %>
                        <%= annual_package_promo.radio_button :promo_name, '', checked: true, id: 'no_annual_single_day_package_selected' %>
                        <div class="radio-button-pair">
                            <%= annual_package_promo.radio_button :promo_name, 'one_child_annual_single_day', id: 'one_child_annual_single_day', class: 'annual-single-day-promo-option' %>
                            <label for="one_child_annual_single_day">One child, annual single day care promo: $400</label>
                        </div>
                        <div class="radio-button-pair">
                            <%= annual_package_promo.radio_button :promo_name, 'two_children_annual_single_day', id: 'two_children_annual_single_day', class: 'annual-single-day-promo-option' %>
                            <label for="two_children_annual_single_day">Two children, annual single day care promo: $700</label>
                        </div>
                        <div class="radio-button-pair">
                            <%= annual_package_promo.radio_button :promo_name, 'three_children_annual_single_day', id: 'three_children_annual_single_day', class: 'annual-single-day-promo-option' %>
                            <label for='three_children_annual_single_day'>Three children, annual single day care promo: $900</label>
                        </div>
                    <% end %>
                </div>
                

                <br><%= f.label :coupon_code, "Coupon Code", class: "f6 fw7 db mb1" %>
                <%= f.text_field :coupon_code, placeholder: "Coupon Code", class: "input-rest ba b--black-20 pa2 mb1 db w-100" %>
			</div>

			<div>
				<h2 class="f6 lh-title ttu tracked mt4 mb0 pv3 orange relative left--1-ns">5. Payment</h2>
			</div>

			<%= f.check_box :agree_to_tos %>
			<%= f.label :agree_to_tos, "I Agree To <a href='/before-and-afterschool-terms-of-service' target='_blank'>The Terms of Service</a>".html_safe %><br/><br/>

			<%= f.hidden_field :customer_id, value: current_customer_user.customer.id %>
			<%= f.hidden_field :referrer, value: 'after_school' %>

            <div class="total-payment-section">
                <div class="shopping-cart-icon"><%= image_tag 'shopping-cart.png' %></div>
                <div class="key-value-pair">
                    <div class="key">Deposit fee: </div>
                    <div class="value" id="deposit-fee-value">$100</div>
                </div>
                <div class="key-value-pair">
                    <div class="key">Registration fee: </div>
                    <div class="value" id="registration-fee-value">$25</div>
                </div>
                <div class="key-value-pair">
                    <div class="key">Annual Package fee: </div>
                    <div class="value" id="annual-package-value">$0</div>
                </div>
                <div class="key-value-pair">
                    <div class="key">Total amount due: </div>
                    <div class="value" id="total-amount-value">$125</div>
                </div>
            </div>

			<%= render "payment_section", f: f %>
		</div>
	<% end %>
</div>

web-app/app/views/registration_records/day_care.html.erb
<div class="w-100 w-80-m w-50-l center pa3">
	<h1 class="f3 f2-ns lh-copy tc">Day Care</h1>

	<div id="js-daycare-code-entry">
		<p class="lh-copy tl"><b>Note: You must have been accepted to day care before filling out this form. Please enter the code provided by your location director below:</b></p>

		<input placeholder="Day Care Code" type="text" class="input rest ba b--black-20 pa2 mb1 db w-100" name="daycare-code" id="js-daycare-code">
		<button class="w-100 pointer bg-orange white ph3 pv2 dim outline-0 ba b--black-20 mt3" id="js-daycare-code-submit">Submit</button>
	</div>

	<div id="js-daycare-wrapper">
		<%= form_for @registration_record do |f| %>
			<% if @registration_record.errors.any? %>
				<div id="errorExplanation">
					<h2>Your were NOT charged. <%= pluralize(@registration_record.errors.count, "error") %> prohibited this record from being saved:</h2>
					<ul>
					<% @registration_record.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
					<% end %>
					</ul>
				</div>
			<% end %>

			<div class="mb3 center">
				<h2 class="f6 lh-title ttu tracked mv0 pv3 orange relative left--1-ns">1. Pick a Location</h2>
				<div>
					<%= f.select :location, options_for_select(Location.includes(:programs).where('programs.name' => "Day Care", 'programs.active' => "true").order(:name).map{|location| [location.dropdown_display_name('Day Care'), location.name]}, @registration_record.location), { include_blank: true }, { class: "bg-white ba b--black-20 pa3 mb1 db", data: { program: "Day Care" } } %>

					<div id="js-location">
					</div>

					<div id="js-capacity-message">
					</div>
				</div>
			</div>

			<div id="js-capacity-wrapper">
				<h2 class="f6 lh-title ttu tracked mt4 mb0 pv3 orange relative left--1-ns">2. Child(ren)’s Info</h2>
				<p class="mt0">Accepting children <b id="js-minimum-age">5</b> years old and up at this location.</p>
				<div id="child-records">
					<%= f.fields_for :child_records do |child_record| %>
						<%= render "request_day_care_tour_child_record_fields", f: child_record %>

						<div class="links list pa0 ma0">
							<%= link_to_add_association 'Add New Child', f, :child_records, partial: 'registration_records/request_day_care_tour_child_record_fields', class: "pointer ph3 pv2 bg-green white outline-0 ba b--black-20 mb3 js-child-records-add" %>
						</div>
					<% end %>
				</div>

				<div>
					<h2 class="f6 lh-title ttu tracked mt4 mb0 pv3 orange relative left--1-ns">3. Start Date</h2>
					<div class="mb3 center">
						<%= f.fields_for :day_care_record do |day_care_record_fields| %>
						<%= day_care_record_fields.label :start_date, class: "f6 fw7 db mb1" %>
						<%= day_care_record_fields.text_field :start_date, class: "input rest ba b--black-20 pa2 mb1 db w-100 date-format", placeholder: 'yyyy-mm-dd' %>
						<% end %>
					</div>
				</div>

				<%= f.check_box :agree_to_tos %>
				<%= f.label :agree_to_tos, "I Agree To <a href='/request-day-care-tour-terms-of-service' target='_blank'>The Terms of Service</a>".html_safe %><br/>

				<%= f.hidden_field :customer_id, value: current_customer_user.customer.id %>
				<%= f.hidden_field :referrer, value: 'day_care' %>

				<%= f.submit 'Submit', class: "w-100 pointer bg-orange white ph3 pv2 dim outline-0 ba b--black-20 mt3" %>
			</div>
		<% end %>
	</div>
</div>