web-app/config/routes.rb
require "resque_web"
Rails.application.routes.draw do

  get 'purchases/shop'

  mount ResqueWeb::Engine => "/resque_web"

	get 'customer_users/edit_personal_information'
	get 'customer_users/edit_billing_information'

	# User Accessible Site

	# Shop
	get 	'shop',							to: 'purchases#shop'
	get 	'add-to-cart/:id',				to: 'purchases#add_to_cart'
	post	'add-to-cart',					to: 'purchases#create_order'
	get		'cart-overview',				to: 'purchases#cart_overview',			as: 'cart_overview'
	delete  'cancel-order/:id',				to: 'purchases#delete_order',			as: 'delete_order'
	post 	'orders/purchase',				to: 'purchases#create',					as: 'purchase_orders'
	get		'successful-transaction/:id', 	to: 'purchases#successful_purchase',	as: 'successful_transaction'

	devise_for :customer_users, controllers: { registrations: 'registrations', passwords: 'api/v1/customer_user_passwords' }
	authenticated :customer_user do
		root 'dashboard#index', as: "authenticated_root"
	end
	devise_scope :customer_user do
		root "devise/sessions#new"
	end
	resources :customers, only: [:create, :update]
	resources :invoices, only: [:show, :index] do
		post 'submit_payment', on: :collection
	end
	resources :receipts, only: [:index, :show] do
		get 'summative_receipt', as: :summative, on: :collection
	end	

	resources :customer_users do
		get :edit_personal_information, on: :collection
		get :edit_billing_information, on: :collection
		post :update_card, on: :collection
		post :add_card, on: :collection
		post :unlink_card, on: :collection
		post :update_auto_pay, on: :collection
	end

	resources :locations do
		get 'get_address', on: :collection
		get 'get_minimum_age', on: :collection
		get 'before_and_after_school_availability', on: :collection
	end
	resources :programs do
		get 'get_capacity', on: :collection
		get 'get_single_day_dates', on: :collection
		get 'get_program', 		on: :collection
		get 'get_summer_camp_weeks', on: :collection
		get 'get_vacation_camp_schedules', on: :collection
	end

	

	get 'registration_information' => 'dashboard#registration_information'
	get '/registration_information/:id', to: 'dashboard#registration_information_show', as: 'registration_information_show'

	resources :cit_records, only: :create
	get 'cit_registration' => 'cit_records#registration'
	get 'cit-registration' => 'cit_records#registration'

	resources :registration_records, only: :create
	get 'single_day' => 'registration_records#single_day'
	get 'single-day' => 'registration_records#single_day'
	get 'single-day-terms-of-service' => 'static_pages#single_day_terms_of_service'

	get 'request_day_care_tour' => 'registration_records#request_day_care_tour'
	get 'request-day-care-tour' => 'registration_records#request_day_care_tour'
	get 'request-day-care-tour-terms-of-service' => 'static_pages#request_day_care_tour_terms_of_service'

	get 'day_care' => 'registration_records#day_care'
	get 'day-care' => 'registration_records#day_care'

	get 'before_and_afterschool' => 'registration_records#before_and_afterschool'
	get 'before-and-afterschool' => 'registration_records#before_and_afterschool'
	get 'before-and-afterschool-terms-of-service' => 'static_pages#before_and_afterschool_terms_of_service'
	get 'before-and-afterschool-rates' => 'static_pages#before_and_after_school_rates'
	get 'no-deposit-before-and-afterschool' => 'registration_records#no_deposit_before_and_afterschool'

	get 'groupon-summer-camp' => 'registration_records#groupon_summer_camp'
	get 'summer_camp' => 'registration_records#summer_camp'
	get 'summer-camp' => 'registration_records#summer_camp'
	get 'summer-camp-terms-of-service' => 'static_pages#summer_camp_terms_of_service'

	get 'vacation_camp' => 'registration_records#vacation_camp'
	get 'vacation-camp' => 'registration_records#vacation_camp'
	get 'vacation-camp-terms-of-service' => 'static_pages#vacation_camp_terms_of_service'

	get 'success' => 'registration_records#success'
	get 'cit_success' => 'cit_records#success'

	

	# Admin Panel
	namespace :admin do
		get '' => 'registration_records#index'
		get 'home' => 'registration_records#index'
		get 'dashboard' => 'dashboard#dashboard'
		get 'payroll' => 'payrolls#home'

		# shop
		get 'shop-purchases', 		to: 'purchases#index',		as: 'shop_purchases'
		get 'purchase-details/:id',	to: 'purchases#details',	as: 'purchase_details'

		# products
		get 'products',				to:	'products#index'

		devise_for :users, controllers: { omniauth_callbacks: "admin/omniauth_callbacks", registrations: "admin/registrations", sessions: "admin/sessions" }
		authenticated :user do
			root 'registration_records#index', as: "authenticated_root"
		end
		devise_scope :user do
			root "devise/sessions#new"
		end
        get  'new-invoices/:id'     => 'registration_records#new_invoices'   , as: 'new_invoices'
        patch 'create-invoices/:id'  => 'registration_records#create_invoices', as: 'create_invoices'

		get '/payment_records/:id' => 'registration_records#show' # makes old routes work still
		resources :registration_records do
			put 'approve', on: :member
			put 'email', on: :member
		end
		resources :cit_records
		resources :locations
		resources :programs
		resources :discounts
		resources :invoices
		resources :customers

		# new vacation_camp_schedule
		get		'programs/:id/new_vacation_camp_schedule',		to: 'programs#new_vacation_camp_schedule', as: 'new_camp_schedule'
		post	'programs/create_new_vacation_camp_schedule',	to: 'programs#create_vacation_camp_schedule', as: 'create_camp_schedule'
        
        # update vacation camp enrollment
		post    'update_vacation_camp_enrollment',              to: 'registration_records#update_vacation_camp_enrollment', as: 'update_vacation_record'
		
		scope :api do
			get 	'monthly-summary',			to: 'api/dashboard#monthly_summary'
			get 	'yearly-summary',			to: 'api/dashboard#yearly_summary'
			get 	'search-customer',			to: 'api/dashboard#search_customer'
			get 	'customer-information',		to: 'api/dashboard#customer_information'
			get 	'program-breakdown', 		to: 'api/dashboard#program_breakdown'
			get 	'programs-summary',			to: 'api/dashboard#programs_summary'
			get		'receipt-information/:id',	to: 'api/dashboard#receipt_information'
			post 	'update-receipt',			to: 'api/dashboard#receipt_update'
		end

		# payroll routes
		scope :payroll do
			get		'accessible-locations/:id',									to: 'payrolls#retrieve_accessible_payroll_locations'
			post	'add-new-payroll-employee', 								to: 'payrolls#add_new_payroll_employee'
			get		'retrieve-payroll-location-information/:location_id/:date',	to: 'payrolls#retrieve_payroll_location_information'
			post	'delete-payroll-employee',									to: 'payrolls#delete_payroll_employee'
			post	'update-payroll-employee-information',						to: 'payrolls#update_payroll_employee_information'
			post	'create-payroll-hour-for-new-employee',						to: 'payrolls#create_payroll_hour_for_new_employee'
			post	'update-payroll-employee-logged-hours',						to: 'payrolls#update_payroll_employee_logged_hours'
			get		'retrieve-all-payroll-locations',							to: 'payrolls#retrieve_all_payroll_locations'
			post	'add-new-payroll-location',									to: 'payrolls#add_new_payroll_location'
			get		'retrieve-all-administrators',								to: 'payrolls#retrieve_all_administrators'
			get		'retrieve-all-authorized-administrators/:location_id',		to: 'payrolls#retrieve_all_authorized_administrators'
			post	'revoke-access-to-payroll-location',						to: 'payrolls#revoke_access_to_payroll_location'
			post	'authorize-access-to-payroll-location',						to: 'payrolls#authorize_access_to_payroll_location'
			post	'update-payroll-location-name',								to: 'payrolls#update_payroll_location_name'
			get		'retrieve-all-payroll-locations-breakdown/:year/:month',	to: 'payrolls#retrieve_all_payroll_locations_breakdown'
			get		'retrieve-all-employees-of-payroll-location/:location_id',	to: 'payrolls#retrieve_all_employees_of_payroll_location'
			post	'log-employee-absence',										to: 'payrolls#log_employee_absence'
			get		'payroll-trend-analysis/:year/:month/:location_id',			to: 'payrolls#retrieve_payroll_location_information_for_trend_analysis'
		end
	end

	# API
	namespace :api, default: { format: :json } do
		scope :v1 do
			post '/test' 							=> 'v1/payments#test'
			post '/payments' 						=> 'v1/payments#create'
			post '/invoices' 						=> 'v1/invoices#generate' # callback api for temporize to generate invoices
			post '/invoices/overdue/end-of-month-afterschool-notification'		=> 'v1/invoices#end_of_month_afterschool_ultimatum' # callback for overdue invoices every end of month for families
			post '/invoices/overdue/fee'			=> 'v1/invoices#generate_late_fees' # generate overdue fees
			post '/invoices/autopay'				=> 'v1/invoices#autopay_invoices' # autopay invoices
			post '/invoices/overdue/one-week'		=> 'v1/invoices#overdue_by_one_week' # send email notification for customer and Tom every 5th of the month
			post '/invoices/unpaid/daycare'			=> 'v1/invoices#notify_tom_for_unpaid_daycare_invoices'
			post '/records/obsolete/afterschool'	=> 'v1/obsolete_records#update_obsolete_before_and_afterschool_records' # update obsolete after school registrations
			post '/records/obsolete/single-day'		=> 'v1/obsolete_records#update_obsolete_single_day_registrations' # obsolete single day registrations
			post '/records/obsolete/summer-camp'	=> 'v1/obsolete_records#update_obsolete_summer_camp_registrations' # obsolete summer camp registrations
			post '/records/obsolete/vacation-camp'	=> 'v1/obsolete_records#update_obsolete_vacation_camp_registrations' # obsolete vacation camp records
			post '/invoices/overdue/last-month'		=> 'v1/invoices#unpaid_invoices_last_month'
			post '/invoices/unpaid/after-school'	=> 'v1/invoices#unpaid_afterschool_invoices'
            post '/invoices/summer-camp/due'        => 'v1/invoices#due_summer_camp_invoices'
			post '/invoices/summer-camp/overdue'    => 'v1/invoices#overdue_summer_camp_invoices'

web-app/app/models/receipt.rb
class Receipt < ActiveRecord::Base
    belongs_to :registration_record
    belongs_to :invoice
    belongs_to :customer
    belongs_to :purchase

    def format_self
        {
            id: self.id,
            amount: "$#{self.amount.to_i}",
            program_name: self.program_name,
            payment_for: self.payment_for
        }
    end
    
end

web-app/app/helpers/receipt_helper.rb
module ReceiptHelper
    def date_of_service(receipt)
        if receipt.program_name == "Single Day"
            if receipt.registration_record.single_day_record.present?
                if receipt.registration_record.single_day_record.single_day_date.present?
                    receipt.registration_record.single_day_record.single_day_date.date.to_formatted_s(:long)
                else
                    receipt.registration_record.single_day_record.created_at.to_formatted_s(:long)
                end
            else
                "#{receipt.registration_record.annual_single_day_promo_record.year_cycle} (Year-round)"
            end
        elsif receipt.program_name == "Vacation Camp"
            result = ""
            if receipt.registration_record.vacation_camp_records.present?
                result = receipt.registration_record.vacation_camp_records.map do | rec |
                    "#{rec.vacation_camp_schedule.schedule_summary}"
                end
                result[result.length - 1] = result[result.length - 1].gsub("|", "")
                result = result.join(' ')
            end
            result
        elsif receipt.program_name == "After School"
            if receipt.registration_record_id.present?
                if receipt.payment_for.include? 'Deposit'
                    if receipt.registration_record.before_and_afterschool_record.present?
                        format_date(receipt.registration_record.before_and_afterschool_record.start_date)
                    else
                        format_date(receipt.registration_record.created_at.to_date)
                    end
                    
                elsif receipt.payment_for.include? 'Invoice'
                    beginning_of_month = receipt.invoice.due_date.beginning_of_month
                    end_of_month = receipt.invoice.due_date.end_of_month
                    "#{format_date(beginning_of_month)} - #{format_date(end_of_month)}"
                end
            end
        elsif receipt.program_name == "Summer Camp"
            if receipt.registration_record_id.present?
                summer_camp_record = receipt.registration_record.summer_camp_record
                program = summer_camp_record.registration_record.program
                weeks_attending = []
                summer_camp_record.attributes.each do |attr_name, attr_value|
                    if attr_value.class == TrueClass || attr_value.class == FalseClass
                        if attr_value
                            weeks_attending << "#{attr_name}"
                        end
                    end
                end
                weeks_attending = format_summer_camp_week_names(weeks_attending)
                result = program.summer_camp_weeks.to_a.keep_if do |week|
                    weeks_attending.any? { |attended_week| week.name.downcase.include? attended_week }
                end
                result.sort
            end
        elsif receipt.program_name == "Day Care"
            "#{format_date(receipt.invoice.due_date)} - #{format_date(receipt.invoice.due_date + 4.days)} "
        end
	end

    def pluralize_child_count(receipt)
        programs = ["Single Day", "Vacation Camp", "After School", 'Summer Camp']
        if programs.any? {|program| program == receipt.program_name }
			'Child'.pluralize(receipt.registration_record.child_records.count)
		end
    end
    
    def child_record_present?(receipt)
        programs = ["Single Day", "Vacation Camp", "After School", "Summer Camp", "Day Care"]
        if programs.any? {|program| program == receipt.program_name }
            receipt.registration_record.child_records.present?
        end
    end

    def receipt_child_records(receipt)
        programs = ["Single Day", "Vacation Camp", "After School", "Summer Camp", "Day Care"]
        if programs.any? {|program| program == receipt.program_name }
            receipt.registration_record.child_records
        end
    end

    def label_for_date_of_service(receipt)
        programs = ["Vacation Camp", "Summer Camp", "Day Care"]
        if programs.any? {|program| program == receipt.program_name }
            "Dates of Service: "
        else
            if receipt.program_name == "Single Day"
                "Date of Service: "
            elsif receipt.program_name == 'After School'
                if receipt.payment_for.include? 'Deposit'
                    "Service Start Date: "
                elsif receipt.payment_for.include? 'Invoice'
                    "Dates of Service: "
                end
            end 
        end
    end

    def format_date date
        date.to_formatted_s(:long)
    end

    def format_old_vacation_camp_schedule(vacation_camp_record)
        month = vacation_camp_record.month
        matched_month = ''
        %w[december february april].each do |el|
            unless month.match(el).nil?
                matched_month = el
            end
        end
        matched_month.capitalize
    end

    def format_summer_camp_week_names weeks_attending
        result = weeks_attending.map do |el|
            case el
                when 'week_one'
                    'week 1'
                when 'week_two'
                    'week 2'
                when 'week_three'
                    'week 3'
                when 'week_four'
                    'week 4'
                when 'week_five'
                    'week 5'
                when 'week_six'
                    'week 6'
                when 'week_seven'
                    'week 7'
                when 'week_eight'
                    'week 8'
                when 'week_nine'
                    'week 9'
                when 'week_ten'
                    'week 10'
                else
                    el
            end
        end
    end

    def summer_camp_week_date_of_service invoice_due_date
        "#{format_date(invoice_due_date)} - #{format_date(invoice_due_date + 4.days)}"
    end

end

web-app/app/views/receipts/_child.html.erb
<div class="receipt-child-record">
    <div class="full-name">
        <div class="name">Name: </div>
        <div class="value"> <%= child.full_name %></div>
    </div>
    <div class="age">
        <div class="name">Age: </div>
        <div class="value"> <%= child.age %></div>
    </div>
</div>

web-app/app/views/receipts/_receipts.html.erb
 <table>
    <tr>
        <th>Date of Issuance</th>
        <th>Program name</th>
        <th>Payment for</th>
        <th>Amount</th>
        <th>&nbsp;</th>
    </tr>
    <% receipts.each do |rec| %>
        <tr>
            <td><%= rec.created_at.to_date.to_formatted_s(:long)%></td>
            <td><%= rec.program_name %></td>
            <td><%= rec.payment_for%></td>
            <td>$<%= rec.amount.to_i %></td>
            <td><%= link_to "View receipt", rec %></td>
        </tr>
    <% end %>
</table>

web-app/app/views/receipts/index.html.erb
<div class="receipts">
    <% if @current_customer.receipts.present? %>
        <h4>Receipts</h4>
        <div class="summative-receipt-button-container">
            <%= link_to "Summative Receipt", summative_receipts_path, class: "asr-button" %>
        </div>
        <div class="container">
            <div class="table-container">
            <%= render 'receipts', receipts: @receipts %>
            </div>
            <%= paginate @receipts, window: 2 %>           
        </div>
    <% else %>
        <h4 id="no-receipts">No Invdividual Receipts to display</h4>
        <div class="no-receipts-summative-container">
            <%= link_to "Summative Receipt", summative_receipts_path, class: "asr-button" %>
        </div>
    <% end %>
</div>

web-app/app/views/receipts/show.html.erb
<div class="receipt-show">
    <div class="container">
        <div class="header-container">
            <h4 id="tsl-header">TSL Adventures</h4>
            <button class="print-button" onClick="window.print()">Print Preview</button>
        </div>
        <div class="company-info">
            <div class="text">
                <p>183 Schoolhouse Rd</p>
                <p>Albany, NY 12203</p>
                <p>Fax: 518-456-0762</p>
                <p>Email: TSLadventures@gmail.com</p>
                <p>Website: www.tsladventures.net</p>
            </div>
            <%= image_tag '/assets/new-logo.png', id: 'logo' %>
        </div>
        <h4 id="payment-header">Payment Receipt</h4>
        <div class="issuance-date">
            <span class="receipt-number">Receipt ID: <strong><%= @receipt.id %></strong></span>
            <span><strong>Date: </strong><%= @receipt.created_at.to_date.to_formatted_s(:long)%></span>  
        </div>
        <div class="payment">
            <div class="customer">
                <div class="name">
                    Payment received from:
                </div>
                <div class="value">
                    <%= @receipt.customer.name %>
                </div>
            </div>
            <div class="amount">
                <div class="name">
                    Amount: 
                </div>
                <div class="value">
                    $<%= number_with_precision(@receipt.amount, :precision => 2, :delimiter => ' ,') %>
                </div>
            </div>
        </div>
        <div class="payment-for">
            <div class="service-name">
                <div class="name">
                    Payment for:
                </div>
                 <div class="value">
                    <%= @receipt.payment_for %>
                </div>
            </div>
           <div class="service-date">
               <div class="name">
                   <%= label_for_date_of_service(@receipt) %>
               </div>
               <div class="value">
                    <% if @receipt.registration_record.present? %>
                        <% if @receipt.registration_record.program.name == 'Summer Camp' %>
                            <% if @receipt.payment_for.include? 'Deposit' %>
                                <div class="selected-summer-camp-weeks">
                                    <% date_of_service(@receipt).each do |week| %>
                                        <div class="data-row">
                                            <%= week.display_name %>
                                        </div>
                                    <% end %>
                                </div>
                            <% elsif @receipt.payment_for.include? 'Invoice' %>
                                <%= summer_camp_week_date_of_service(@receipt.invoice.due_date) %>
                            <% end %>
                        <% else %>
                            <%= date_of_service(@receipt) %>
                        <% end %>
                    <% end %>
               </div>
           </div>
        </div>
        <% if @receipt.registration_record.present? %>
            <% if @receipt.registration_record.program.name == 'Summer Camp' %>
                <h5>Services are rendered for the whole week for every indicated item.</h5>    
            <% end %>
        <% end %>
        <% if @receipt.registration_record.present? %>
            <h4 id="child-record"><%= pluralize_child_count(@receipt)%> Information</h4>
            <div class="child-record-table">
                <div class="container">
                    <% if child_record_present?(@receipt) %>
                        <% receipt_child_records(@receipt).each do |child| %>
                            <%= render partial: 'child', locals: {child: child} %>
                        <% end %>
                    <% end %>
                </div>
            </div>
        <% end %>

        <% if @receipt.purchase.present? %>
            <div class="purchased-items">
                <div class="key">
                    Items: 
                </div>
                <div class="value">
                    <% if false%>
                        <ul class="item-list">
                            <% @receipt.purchase.order_details.each do |order| %>
                                <li><%= order %></li>
                            <% end %>
                        </ul>
                    <% end %>

                    <table>
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Size</th>
                                <th>Price</th>
                                <th>Quantity</th>
                                <th>Subtotal</th>
                            </tr>
                        </thead>
                        <tbody>
                            <% @receipt.purchase.order_details.each do |order| %>
                                <tr>
                                    <td><%= order.product.name %></td>
                                    <td><%= order.size.name %></td>
                                    <td>$<%= number_with_precision(order.size.price, precision: 2) %></td>
                                    <td><%= order.quantity %></td>
                                    <td>$<%= number_with_precision(order.total_amount, precision: 2) %></td>
                                </tr>
                            <% end %>
                        </tbody>
                    </table>
                </div>
            </div>
        <% end %>

        <div class="tax">
            <h4 class="company-tax-label">Company Tax ID Number: </h4>
            <span>26-3268474</span>
        </div>
        
    </div>
</div>

<div class="receipt-disclaimer">
    For inquiries about your receipt, please contact the Administrator and provide them the Receipt ID. (This message is not included when this receipt is printed)
</div>