web-app/config/routes.rb
require "resque_web"
Rails.application.routes.draw do

  get 'purchases/shop'

  mount ResqueWeb::Engine => "/resque_web"

	get 'customer_users/edit_personal_information'
	get 'customer_users/edit_billing_information'

	# User Accessible Site

	# Shop
	get 	'shop',							to: 'purchases#shop'
	get 	'add-to-cart/:id',				to: 'purchases#add_to_cart'
	post	'add-to-cart',					to: 'purchases#create_order'
	get		'cart-overview',				to: 'purchases#cart_overview',			as: 'cart_overview'
	delete  'cancel-order/:id',				to: 'purchases#delete_order',			as: 'delete_order'
	post 	'orders/purchase',				to: 'purchases#create',					as: 'purchase_orders'
	get		'successful-transaction/:id', 	to: 'purchases#successful_purchase',	as: 'successful_transaction'

	devise_for :customer_users, controllers: { registrations: 'registrations', passwords: 'api/v1/customer_user_passwords' }
	authenticated :customer_user do
		root 'dashboard#index', as: "authenticated_root"
	end
	devise_scope :customer_user do
		root "devise/sessions#new"
	end
	resources :customers, only: [:create, :update]
	resources :invoices, only: [:show, :index] do
		post 'submit_payment', on: :collection
	end
	resources :receipts, only: [:index, :show] do
		get 'summative_receipt', as: :summative, on: :collection
	end	

	resources :customer_users do
		get :edit_personal_information, on: :collection
		get :edit_billing_information, on: :collection
		post :update_card, on: :collection
		post :add_card, on: :collection
		post :unlink_card, on: :collection
		post :update_auto_pay, on: :collection
	end

	resources :locations do
		get 'get_address', on: :collection
		get 'get_minimum_age', on: :collection
		get 'before_and_after_school_availability', on: :collection
	end
	resources :programs do
		get 'get_capacity', on: :collection
		get 'get_single_day_dates', on: :collection
		get 'get_program', 		on: :collection
		get 'get_summer_camp_weeks', on: :collection
		get 'get_vacation_camp_schedules', on: :collection
	end

	

	get 'registration_information' => 'dashboard#registration_information'
	get '/registration_information/:id', to: 'dashboard#registration_information_show', as: 'registration_information_show'

	resources :cit_records, only: :create
	get 'cit_registration' => 'cit_records#registration'
	get 'cit-registration' => 'cit_records#registration'

	resources :registration_records, only: :create
	get 'single_day' => 'registration_records#single_day'
	get 'single-day' => 'registration_records#single_day'
	get 'single-day-terms-of-service' => 'static_pages#single_day_terms_of_service'

	get 'request_day_care_tour' => 'registration_records#request_day_care_tour'
	get 'request-day-care-tour' => 'registration_records#request_day_care_tour'
	get 'request-day-care-tour-terms-of-service' => 'static_pages#request_day_care_tour_terms_of_service'

	get 'day_care' => 'registration_records#day_care'
	get 'day-care' => 'registration_records#day_care'

	get 'before_and_afterschool' => 'registration_records#before_and_afterschool'
	get 'before-and-afterschool' => 'registration_records#before_and_afterschool'
	get 'before-and-afterschool-terms-of-service' => 'static_pages#before_and_afterschool_terms_of_service'
	get 'before-and-afterschool-rates' => 'static_pages#before_and_after_school_rates'
	get 'no-deposit-before-and-afterschool' => 'registration_records#no_deposit_before_and_afterschool'

	get 'groupon-summer-camp' => 'registration_records#groupon_summer_camp'
	get 'summer_camp' => 'registration_records#summer_camp'
	get 'summer-camp' => 'registration_records#summer_camp'
	get 'summer-camp-terms-of-service' => 'static_pages#summer_camp_terms_of_service'

	get 'vacation_camp' => 'registration_records#vacation_camp'
	get 'vacation-camp' => 'registration_records#vacation_camp'
	get 'vacation-camp-terms-of-service' => 'static_pages#vacation_camp_terms_of_service'

	get 'success' => 'registration_records#success'
	get 'cit_success' => 'cit_records#success'

	

	# Admin Panel
	namespace :admin do
		get '' => 'registration_records#index'
		get 'home' => 'registration_records#index'
		get 'dashboard' => 'dashboard#dashboard'
		get 'payroll' => 'payrolls#home'

		# shop
		get 'shop-purchases', 		to: 'purchases#index',		as: 'shop_purchases'
		get 'purchase-details/:id',	to: 'purchases#details',	as: 'purchase_details'

		# products
		get 'products',				to:	'products#index'

		devise_for :users, controllers: { omniauth_callbacks: "admin/omniauth_callbacks", registrations: "admin/registrations", sessions: "admin/sessions" }
		authenticated :user do
			root 'registration_records#index', as: "authenticated_root"
		end
		devise_scope :user do
			root "devise/sessions#new"
		end
        get  'new-invoices/:id'     => 'registration_records#new_invoices'   , as: 'new_invoices'
        patch 'create-invoices/:id'  => 'registration_records#create_invoices', as: 'create_invoices'

		get '/payment_records/:id' => 'registration_records#show' # makes old routes work still
		resources :registration_records do
			put 'approve', on: :member
			put 'email', on: :member
		end
		resources :cit_records
		resources :locations
		resources :programs
		resources :discounts
		resources :invoices
		resources :customers

		# new vacation_camp_schedule
		get		'programs/:id/new_vacation_camp_schedule',		to: 'programs#new_vacation_camp_schedule', as: 'new_camp_schedule'
		post	'programs/create_new_vacation_camp_schedule',	to: 'programs#create_vacation_camp_schedule', as: 'create_camp_schedule'
        
        # update vacation camp enrollment
		post    'update_vacation_camp_enrollment',              to: 'registration_records#update_vacation_camp_enrollment', as: 'update_vacation_record'
		
		scope :api do
			get 	'monthly-summary',			to: 'api/dashboard#monthly_summary'
			get 	'yearly-summary',			to: 'api/dashboard#yearly_summary'
			get 	'search-customer',			to: 'api/dashboard#search_customer'
			get 	'customer-information',		to: 'api/dashboard#customer_information'
			get 	'program-breakdown', 		to: 'api/dashboard#program_breakdown'
			get 	'programs-summary',			to: 'api/dashboard#programs_summary'
			get		'receipt-information/:id',	to: 'api/dashboard#receipt_information'
			post 	'update-receipt',			to: 'api/dashboard#receipt_update'
		end

		# payroll routes
		scope :payroll do
			get		'accessible-locations/:id',									to: 'payrolls#retrieve_accessible_payroll_locations'
			post	'add-new-payroll-employee', 								to: 'payrolls#add_new_payroll_employee'
			get		'retrieve-payroll-location-information/:location_id/:date',	to: 'payrolls#retrieve_payroll_location_information'
			post	'delete-payroll-employee',									to: 'payrolls#delete_payroll_employee'
			post	'update-payroll-employee-information',						to: 'payrolls#update_payroll_employee_information'
			post	'create-payroll-hour-for-new-employee',						to: 'payrolls#create_payroll_hour_for_new_employee'
			post	'update-payroll-employee-logged-hours',						to: 'payrolls#update_payroll_employee_logged_hours'
			get		'retrieve-all-payroll-locations',							to: 'payrolls#retrieve_all_payroll_locations'
			post	'add-new-payroll-location',									to: 'payrolls#add_new_payroll_location'
			get		'retrieve-all-administrators',								to: 'payrolls#retrieve_all_administrators'
			get		'retrieve-all-authorized-administrators/:location_id',		to: 'payrolls#retrieve_all_authorized_administrators'
			post	'revoke-access-to-payroll-location',						to: 'payrolls#revoke_access_to_payroll_location'
			post	'authorize-access-to-payroll-location',						to: 'payrolls#authorize_access_to_payroll_location'
			post	'update-payroll-location-name',								to: 'payrolls#update_payroll_location_name'
			get		'retrieve-all-payroll-locations-breakdown/:year/:month',	to: 'payrolls#retrieve_all_payroll_locations_breakdown'
			get		'retrieve-all-employees-of-payroll-location/:location_id',	to: 'payrolls#retrieve_all_employees_of_payroll_location'
			post	'log-employee-absence',										to: 'payrolls#log_employee_absence'
			get		'payroll-trend-analysis/:year/:month/:location_id',			to: 'payrolls#retrieve_payroll_location_information_for_trend_analysis'
		end
	end

	# API
	namespace :api, default: { format: :json } do
		scope :v1 do
			post '/test' 							=> 'v1/payments#test'
			post '/payments' 						=> 'v1/payments#create'
			post '/invoices' 						=> 'v1/invoices#generate' # callback api for temporize to generate invoices
			post '/invoices/overdue/end-of-month-afterschool-notification'		=> 'v1/invoices#end_of_month_afterschool_ultimatum' # callback for overdue invoices every end of month for families
			post '/invoices/overdue/fee'			=> 'v1/invoices#generate_late_fees' # generate overdue fees
			post '/invoices/autopay'				=> 'v1/invoices#autopay_invoices' # autopay invoices
			post '/invoices/overdue/one-week'		=> 'v1/invoices#overdue_by_one_week' # send email notification for customer and Tom every 5th of the month
			post '/invoices/unpaid/daycare'			=> 'v1/invoices#notify_tom_for_unpaid_daycare_invoices'
			post '/records/obsolete/afterschool'	=> 'v1/obsolete_records#update_obsolete_before_and_afterschool_records' # update obsolete after school registrations
			post '/records/obsolete/single-day'		=> 'v1/obsolete_records#update_obsolete_single_day_registrations' # obsolete single day registrations
			post '/records/obsolete/summer-camp'	=> 'v1/obsolete_records#update_obsolete_summer_camp_registrations' # obsolete summer camp registrations
			post '/records/obsolete/vacation-camp'	=> 'v1/obsolete_records#update_obsolete_vacation_camp_registrations' # obsolete vacation camp records
			post '/invoices/overdue/last-month'		=> 'v1/invoices#unpaid_invoices_last_month'
			post '/invoices/unpaid/after-school'	=> 'v1/invoices#unpaid_afterschool_invoices'
            post '/invoices/summer-camp/due'        => 'v1/invoices#due_summer_camp_invoices'
			post '/invoices/summer-camp/overdue'    => 'v1/invoices#overdue_summer_camp_invoices'

web-app/app/controllers/admin/purchases_controller.rb
class Admin::PurchasesController < AdminController
    def index
        @locations = Location.where.not('locations.name = ?', 'Counselors in Training')
            .joins(:programs)
            .where('programs.name = ?', 'Summer Camp')
            .order('name ASC')
        @q = Purchase.ransack(params[:q])
        @purchases = @q.result.order('created_at DESC').page(params[:page]).per(10)
    end

    def details
        @purchase = Purchase.find_by(id: params[:id])
    end
end

web-app/app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
    before_action :set_order, only: [:add_to_cart]
    skip_before_action :authenticate_customer_user!, :only => [:shop,:cart_overview,:add_to_cart,:create_order,:create,:delete_order]
    def shop
        @products = Product.all
    end

    def create
        puts params
        if !params[:email].present? && !customer_user_signed_in?
            flash[:error] = "Email required."
            redirect_to cart_overview_path and return
        elsif !params[:name].present? && !customer_user_signed_in?
            flash[:error] = "Name Required."
            redirect_to cart_overview_path and return
        end
        @purchase = Purchase.new(Services::Purchase::Construct.invoke(purchase_params))
        begin
            if @purchase.valid?
                customer_user_signed_in? ? @purchase.create_stripe_charge(params) : @purchase.create_stripe_charge_without_customer(params)
                if @purchase.save
                    puts "-0000000000000000000000"
                    puts customer_user_signed_in?
                    customer_user_signed_in? ? "" : session.delete(:orders)
                    customer_user_signed_in? ? @purchase.update_order_status_to_purchased : @purchase.update_order_status_to_purchased_without_user
                    AdminMailer.notify_tom_of_shop_purchase(@purchase).deliver!         
                    redirect_to successful_transaction_path(@purchase)
                else
                    redirect_to cart_overview_path
                end
            else
                if @purchase.errors.full_messages.include?("Orders can't be blank").present?
                    flash[:error] = "Could not proceed with transaction. Your cart is empty."
                end
                redirect_to cart_overview_path
            end 
        rescue StandardError => error
            f = File.open('log/payment.log','a')
			f.puts "message: #{error.message}, date: #{Time.current}, purchase_id: #{@purchase}"
			f.close
            flash[:error] = error.message
            redirect_to cart_overview_path
        end
    end

    def add_to_cart
        @order = Order.new
        @locations = Location.where.not('locations.name = ?', 'Counselors in Training')
            .joins(:programs)
            .where('programs.name = ?', 'Summer Camp')
            .order('name ASC')
    end

    def create_order
        size = Size.find(order_params[:size_id])
        if size.quantity > 0
            session[:orders] ||= []
            @order = Order.new(order_params)
            if @order.save && customer_user_signed_in?
                flash[:notice] = "Successfully added item to cart"
                redirect_to cart_overview_path
            elsif !customer_user_signed_in?
                session[:orders].push(@order.id)
                puts session[:orders].inspect
                redirect_to cart_overview_path
            else
                render :add_to_cart
            end
        else
            flash[:notice] = "Sorry #{size.name},is out of stock."
            redirect_to '/add-to-cart/' + order_params[:product_id]
        end
    end

    def cart_overview
        @locations = Location.where.not('locations.name = ?', 'Counselors in Training')
            .joins(:programs)
            .where('programs.name = ?', 'Summer Camp')
            .order('name ASC')
        if customer_user_signed_in?
            @orders = current_customer_user.customer.orders.where.not(purchased: true).order('created_at DESC')
        else
            @orders = []
            
            if session[:orders].present?
                @orders = Order.where(:id => session[:orders])
            end
            puts @orders
        end
        @purchase = Purchase.new
    end

    def delete_order
        puts 
        puts params
        @order = Order.find_by(id: params[:id])
        @order.destroy if @order.present?
        session[:orders].delete(params[:id])
        flash[:notice] = "Successfully removed item from your cart"
        redirect_to cart_overview_path
    end

    def successful_purchase
        @receipt = Purchase.find_by(id: params[:id]).receipt
    end

    private

    def order_params
        params.require(:order).permit(
            :product_id,
            :size_id,
            :quantity,
            :customer_id
        )
    end

    def purchase_params
        params.require(:purchase).permit(
            :customer_id,
            :orders,
            :location_id
        )
    end

    def set_order
        @product = Product.find_by(id: params[:id])
    end
end

web-app/app/views/admin/purchases/details.html.erb
<div class="admin-purchase-details">
    <h1>Purchase details</h1>
    <div class="information">
        <h2 class="header">Parent information</h2>
        <div><strong>Name: </strong> <span><%= @purchase.customer.present? ? @purchase.customer.name.titleize : ""%></span></div>
        <div><strong>Email: </strong> <span><%= @purchase.customer.present? ? @purchase.customer.email : ""%></span></div>
        <div><strong>Phone Number: </strong> <span><%= @purchase.customer.present? ? @purchase.customer.phone_number : ""%></span></div>
        <div><strong>Emergency Phone Number: </strong> <span><%= @purchase.customer.present? ? @purchase.customer.emergency_phone_number : ""%></span></div>
        <div><strong>Address: </strong> <span><%=@purchase.customer.present? ?  @purchase.customer.address : ""%></span></div>
    </div>

    <div class="information">
        <h2 class="header">Payment information</h2>
        <div><strong>Payment Platform: </strong> <span>Stripe</span></div>
        <div><strong>Payment URL: </strong> <%= link_to 'Go to stripe', @purchase.payment_url, target: '_blank' %></div>
        <div><strong>Amount Paid:  </strong> <span>$<%= number_with_precision(@purchase.total_amount, precision: 2) %></span></div>
        <div><strong>Customer Identifier: </strong> <span><%= @purchase.customer.present? ? @purchase.customer.stripe_customer_identifier : "" %></span></div>
        <div><strong>Transaction ID: </strong> <span><%= @purchase.customer.present? ? @purchase.customer.address : "" %></span></div>
        <div><strong>Summer Camp Location: </strong> <span><%= @purchase.customer.present? ? @purchase.location.name : "" %></span></div>
    </div>

    <div class="information">
        <h2 class="header">Order details</h2>
    </div>

    <div class="order-details-table-container">
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Size</th>
                    <th>Color</th>
                    <th>Price</th>
                    <th>Quantity</th>
                    <th>Subtotal</th>
                </tr>
            </thead>
            <tbody>
                <% @purchase.order_details.each do |order| %>
                    <tr>
                        <td><%= order.product.name %></td>
                        <td><%= order.size.name.nil? ? "N/A" : order.size.name%></td>
                        <td><%= order.size.color.nil? ? "N/A" : order.size.color %></td>
                        <td>$<%= number_with_precision(order.size.price, precision: 2) %></td>
                        <td><%= order.quantity %></td>
                        <td>$<%= number_with_precision(order.total_amount, precision: 2) %></td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    </div>
</div>

web-app/app/views/admin/purchases/index.html.erb
<div class="admin-purchases-section">
    <h1>Purchases</h1>
    <section class="search-fields-section">
        <div class="search-fields">
            <%= search_form_for @q, url: admin_shop_purchases_path, html: { class: "search-form" } do |f| %>
                <h2>Filter Records</h2>
                <div class="input-pair">
                    <%= f.label :location_id, 'Summer Camp Location' %>
                    <%= f.select :location_id_eq, options_for_select(@locations.collect {|l| [l.name, l.id]}, @q.location_id) %>
                </div>
                <div class="submit-button-container">
                    <%= link_to 'Clear filters', admin_shop_purchases_path, class: 'button' %> <%= f.submit "Search", class: 'button' %>
                </div>
            <% end %>
        </div>
    </section>
    <section class="purchases-summary-section">
        <div class="purchases-table-container">
            <table>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Date of Purchase</th>
                        <th>Quantity</th>
                        <th>Amount Paid</th>
                        <th>Location</th>
                        <th>&nbsp;</th>
                    </tr>
                </thead>
                <tbody>
                    <% @purchases.each do |purch| %>
                    <tr>
                        <td><%= purch.customer.present? ? purch.customer.name.titleize : "" %></td>
                        <td><%= purch.created_at.to_date.to_formatted_s(:long) %></td>
                        <td><%= purch.order_details.pluck(:quantity).reduce(:+) %></td>
                        <td>$<%= number_with_precision(purch.total_amount, precision: 2) %></td>
                        <td><%= purch.location.name %></td>
                        <td><%= link_to 'View', admin_purchase_details_path(purch) %></td>
                    </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
        <%= paginate @purchases %>
    </section>
</div>